"""add exercise unit

Revision ID: c40f8dffd627
Revises: b71a0e3c393a
Create Date: 2026-08-09 22:41:54.990022

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c40f8dffd627"
down_revision: str | Sequence[str] | None = "b71a0e3c393a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercises",
        sa.Column(
            "unit",
            sa.String(length=20),
            server_default=sa.text("'weight_reps'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exercises", "unit")
    # ### end Alembic commands ###
